
enclave-file = "${home}/ccf/lib/libpdoenc.virtual.so"
enclave-type = "virtual"
consensus = "raft"
public-rpc-address = "${host_address}:6606"
rpc-address = "${host_address}:6607"
node-address = "${host_address}:6608"

[start]
network-cert-file = "${home}/ccf/keys/network_cert.pem"
network-enc-pubk-file = "${home}/ccf/keys/network_enc_pubk.pem"
member-info = "${home}/ccf/keys/member0_cert.pem,${home}/ccf/keys/member0_kshare_pub.pem"
gov-script = "${home}/ccf/etc/gov.lua"
